version: '3.8'

services:
  ai-service:
    build:
      context: ./register/ai-service
      dockerfile: Dockerfile
    container_name: roadna-ai-service
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
    restart: always

  backend:
    build:
      context: ./
      dockerfile: ./register/backend/Dockerfile
    container_name: roadna-backend
    ports:
      - "5002:5002"
    depends_on:
      - ai-service
    environment:
      - PORT=5002
      - MONGO_URI=mongodb+srv://admin:Password123@cluster0.9al6iby.mongodb.net/roadna?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=asdslakjdasdasdjl;asdasdhauweiopdaiusdhdd
      - NODE_ENV=production
      - ADMIN_SETUP_KEY=roadna-admin-setup-2024
      - EMAIL_USER=rodnaprojects@gmail.com
      - EMAIL_APP_PASSWORD=yupu gejv rjwg fttc
      - SMS_ALLOW_MOCK=true
      - AI_SERVICE_URL=http://roadna-ai-service:5001
    restart: always
